// This file is auto-generated by @hey-api/openapi-ts

export const PagedSimpleTreeItemResponseModelSchema = {
    required: [
        'total',
        'items'
    ],
    type: 'object',
    properties: {
        total: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int64'
        },
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/SimpleTreeItemResponse'
            }
        }
    }
} as const;

export const SimpleEntityActionExecuteResponseSchema = {
    required: [
        'title',
        'message',
        'isSuccess'
    ],
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        isSuccess: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const SimpleEntityActionRequestSchema = {
    required: [
        'unique',
        'entityType',
        'actionAlias'
    ],
    type: 'object',
    properties: {
        unique: {
            type: 'string'
        },
        entityType: {
            type: 'string'
        },
        actionAlias: {
            type: 'string'
        }
    }
} as const;

export const SimpleEntityActionUrlResponseSchema = {
    required: [
        'url'
    ],
    type: 'object',
    properties: {
        url: {
            type: 'string'
        }
    }
} as const;

export const SimpleTreeItemParentResponseSchema = {
    required: [
        'unique'
    ],
    type: 'object',
    properties: {
        unique: {
            type: 'string'
        },
        entityType: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const SimpleTreeItemResponseSchema = {
    required: [
        'name',
        'icon',
        'entityType',
        'unique',
        'hasChildren',
        'isFolder'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        icon: {
            type: 'string'
        },
        entityType: {
            type: 'string'
        },
        unique: {
            type: 'string'
        },
        hasChildren: {
            type: 'boolean'
        },
        isFolder: {
            type: 'boolean'
        },
        parent: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/SimpleTreeItemParentResponse'
                }
            ]
        }
    }
} as const;

export const SimpleTreeRenderModelSchema = {
    required: [
        'body'
    ],
    type: 'object',
    properties: {
        body: {
            type: 'string'
        }
    }
} as const;

export const TargetPagedModelOfSimpleTreeItemResponseSchema = {
    required: [
        'totalBefore',
        'totalAfter',
        'items',
        'total'
    ],
    type: 'object',
    properties: {
        totalBefore: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        totalAfter: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/SimpleTreeItemResponse'
            }
        },
        total: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int64'
        }
    }
} as const;
