// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetUmbracoSimpleTreesApiV1TreeItemsData, GetUmbracoSimpleTreesApiV1TreeItemsResponses, GetUmbracoSimpleTreesApiV1TreeRenderData, GetUmbracoSimpleTreesApiV1TreeRenderResponses, GetUmbracoSimpleTreesApiV1TreeRootData, GetUmbracoSimpleTreesApiV1TreeRootResponses, PostUmbracoSimpleTreesApiV1EntityActionExecuteData, PostUmbracoSimpleTreesApiV1EntityActionExecuteResponses, PostUmbracoSimpleTreesApiV1EntityActionUrlData, PostUmbracoSimpleTreesApiV1EntityActionUrlResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class SimpleTrees {
    public static postUmbracoSimpleTreesApiV1EntityActionExecute<ThrowOnError extends boolean = true>(options?: Options<PostUmbracoSimpleTreesApiV1EntityActionExecuteData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoSimpleTreesApiV1EntityActionExecuteResponses, unknown, ThrowOnError>({
            url: '/umbraco/SimpleTrees/api/v1/entity-action/execute',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static postUmbracoSimpleTreesApiV1EntityActionUrl<ThrowOnError extends boolean = true>(options?: Options<PostUmbracoSimpleTreesApiV1EntityActionUrlData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoSimpleTreesApiV1EntityActionUrlResponses, unknown, ThrowOnError>({
            url: '/umbraco/SimpleTrees/api/v1/entity-action/url',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getUmbracoSimpleTreesApiV1TreeItems<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSimpleTreesApiV1TreeItemsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSimpleTreesApiV1TreeItemsResponses, unknown, ThrowOnError>({
            url: '/umbraco/SimpleTrees/api/v1/tree/items',
            ...options
        });
    }
    
    public static getUmbracoSimpleTreesApiV1TreeRender<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSimpleTreesApiV1TreeRenderData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSimpleTreesApiV1TreeRenderResponses, unknown, ThrowOnError>({
            url: '/umbraco/SimpleTrees/api/v1/tree/render',
            ...options
        });
    }
    
    public static getUmbracoSimpleTreesApiV1TreeRoot<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSimpleTreesApiV1TreeRootData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSimpleTreesApiV1TreeRootResponses, unknown, ThrowOnError>({
            url: '/umbraco/SimpleTrees/api/v1/tree/root',
            ...options
        });
    }
}
