// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetUmbracoSimpleTreesApiV1TreeItemsData, GetUmbracoSimpleTreesApiV1TreeItemsResponse, GetUmbracoSimpleTreesApiV1TreeRenderData, GetUmbracoSimpleTreesApiV1TreeRenderResponse, GetUmbracoSimpleTreesApiV1TreeRootData, GetUmbracoSimpleTreesApiV1TreeRootResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class SimpleTreesService {
    public static getUmbracoSimpleTreesApiV1TreeItems<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSimpleTreesApiV1TreeItemsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetUmbracoSimpleTreesApiV1TreeItemsResponse, unknown, ThrowOnError>({
            url: '/umbraco/SimpleTrees/api/v1/tree/items',
            ...options
        });
    }
    
    public static getUmbracoSimpleTreesApiV1TreeRender<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSimpleTreesApiV1TreeRenderData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetUmbracoSimpleTreesApiV1TreeRenderResponse, unknown, ThrowOnError>({
            url: '/umbraco/SimpleTrees/api/v1/tree/render',
            ...options
        });
    }
    
    public static getUmbracoSimpleTreesApiV1TreeRoot<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSimpleTreesApiV1TreeRootData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetUmbracoSimpleTreesApiV1TreeRootResponse, unknown, ThrowOnError>({
            url: '/umbraco/SimpleTrees/api/v1/tree/root',
            ...options
        });
    }
    
}