// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetTreeItemsPagedOffsetData, GetTreeItemsPagedOffsetErrors, GetTreeItemsPagedOffsetResponses, GetTreeItemsPagedTargetData, GetTreeItemsPagedTargetErrors, GetTreeItemsPagedTargetResponses, GetTreeRenderData, GetTreeRenderErrors, GetTreeRenderResponses, GetTreeRootPagedOffsetData, GetTreeRootPagedOffsetErrors, GetTreeRootPagedOffsetResponses, GetTreeRootPagedTargetData, GetTreeRootPagedTargetErrors, GetTreeRootPagedTargetResponses, PostEntityActionExecuteData, PostEntityActionExecuteErrors, PostEntityActionExecuteResponses, PostEntityActionUrlData, PostEntityActionUrlErrors, PostEntityActionUrlResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class SimpleTrees {
    public static postEntityActionExecute<ThrowOnError extends boolean = true>(options: Options<PostEntityActionExecuteData, ThrowOnError>): RequestResult<PostEntityActionExecuteResponses, PostEntityActionExecuteErrors, ThrowOnError> {
        return (options.client ?? client).post<PostEntityActionExecuteResponses, PostEntityActionExecuteErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/SimpleTrees/api/v1/entity-action/execute',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postEntityActionUrl<ThrowOnError extends boolean = true>(options: Options<PostEntityActionUrlData, ThrowOnError>): RequestResult<PostEntityActionUrlResponses, PostEntityActionUrlErrors, ThrowOnError> {
        return (options.client ?? client).post<PostEntityActionUrlResponses, PostEntityActionUrlErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/SimpleTrees/api/v1/entity-action/url',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static getTreeItemsPagedOffset<ThrowOnError extends boolean = true>(options?: Options<GetTreeItemsPagedOffsetData, ThrowOnError>): RequestResult<GetTreeItemsPagedOffsetResponses, GetTreeItemsPagedOffsetErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetTreeItemsPagedOffsetResponses, GetTreeItemsPagedOffsetErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/SimpleTrees/api/v1/tree/items/paged-offset',
            ...options
        });
    }
    
    public static getTreeItemsPagedTarget<ThrowOnError extends boolean = true>(options?: Options<GetTreeItemsPagedTargetData, ThrowOnError>): RequestResult<GetTreeItemsPagedTargetResponses, GetTreeItemsPagedTargetErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetTreeItemsPagedTargetResponses, GetTreeItemsPagedTargetErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/SimpleTrees/api/v1/tree/items/paged-target',
            ...options
        });
    }
    
    public static getTreeRender<ThrowOnError extends boolean = true>(options?: Options<GetTreeRenderData, ThrowOnError>): RequestResult<GetTreeRenderResponses, GetTreeRenderErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetTreeRenderResponses, GetTreeRenderErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/SimpleTrees/api/v1/tree/render',
            ...options
        });
    }
    
    public static getTreeRootPagedOffset<ThrowOnError extends boolean = true>(options?: Options<GetTreeRootPagedOffsetData, ThrowOnError>): RequestResult<GetTreeRootPagedOffsetResponses, GetTreeRootPagedOffsetErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetTreeRootPagedOffsetResponses, GetTreeRootPagedOffsetErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/SimpleTrees/api/v1/tree/root/paged-offset',
            ...options
        });
    }
    
    public static getTreeRootPagedTarget<ThrowOnError extends boolean = true>(options?: Options<GetTreeRootPagedTargetData, ThrowOnError>): RequestResult<GetTreeRootPagedTargetResponses, GetTreeRootPagedTargetErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetTreeRootPagedTargetResponses, GetTreeRootPagedTargetErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/SimpleTrees/api/v1/tree/root/paged-target',
            ...options
        });
    }
}
