// This file is auto-generated by @hey-api/openapi-ts

export type PagedISimpleTreeItemModel = {
    total: number;
    items: Array<SimpleTreeItem>;
};

export type SimpleTreeItem = {
    hasChildren: boolean;
    name: string;
    isFolder: boolean;
    icon: string;
    entityType: string;
    unique: string;
    parent?: SimpleTreeItemParent | null;
};

export type SimpleTreeItemParent = {
    entityType: string;
    unique: string;
};

export type SimpleTreeRenderModel = {
    body: string;
};

export type GetUmbracoSimpleTreesApiV1TreeItemsData = {
    body?: never;
    path?: never;
    query?: {
        treeAlias?: string;
        entityType?: string;
        parentUnique?: string;
        skip?: number;
        take?: number;
        foldersOnly?: boolean;
    };
    url: '/umbraco/SimpleTrees/api/v1/tree/items';
};

export type GetUmbracoSimpleTreesApiV1TreeItemsResponses = {
    /**
     * OK
     */
    200: PagedISimpleTreeItemModel;
};

export type GetUmbracoSimpleTreesApiV1TreeItemsResponse = GetUmbracoSimpleTreesApiV1TreeItemsResponses[keyof GetUmbracoSimpleTreesApiV1TreeItemsResponses];

export type GetUmbracoSimpleTreesApiV1TreeRenderData = {
    body?: never;
    path?: never;
    query?: {
        unique?: string;
        entityType?: string;
    };
    url: '/umbraco/SimpleTrees/api/v1/tree/render';
};

export type GetUmbracoSimpleTreesApiV1TreeRenderResponses = {
    /**
     * OK
     */
    200: SimpleTreeRenderModel;
};

export type GetUmbracoSimpleTreesApiV1TreeRenderResponse = GetUmbracoSimpleTreesApiV1TreeRenderResponses[keyof GetUmbracoSimpleTreesApiV1TreeRenderResponses];

export type GetUmbracoSimpleTreesApiV1TreeRootData = {
    body?: never;
    path?: never;
    query?: {
        treeAlias?: string;
        skip?: number;
        take?: number;
        foldersOnly?: boolean;
    };
    url: '/umbraco/SimpleTrees/api/v1/tree/root';
};

export type GetUmbracoSimpleTreesApiV1TreeRootResponses = {
    /**
     * OK
     */
    200: PagedISimpleTreeItemModel;
};

export type GetUmbracoSimpleTreesApiV1TreeRootResponse = GetUmbracoSimpleTreesApiV1TreeRootResponses[keyof GetUmbracoSimpleTreesApiV1TreeRootResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:54813' | (string & {});
};