// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:54813/' | (string & {});
};

/**
 * Represents a paged collection of items with total count.
 */
export type PagedSimpleTreeItemResponseModel = {
    /**
     * Gets or sets the total number of items available.
     */
    total: number | string;
    /**
     * Gets or sets the items in the current page.
     */
    items: Array<SimpleTreeItemResponse>;
};

export type SimpleEntityActionExecuteResponse = {
    title: string;
    isSuccess: boolean;
    message: string;
};

export type SimpleEntityActionRequest = {
    unique: string;
    entityType: string;
    actionAlias: string;
};

export type SimpleEntityActionUrlResponse = {
    url: string;
};

export type SimpleTreeItemParentResponse = {
    unique: string;
    entityType?: null | string;
};

export type SimpleTreeItemResponse = {
    name: string;
    icon: string;
    entityType: string;
    unique: string;
    hasChildren: boolean;
    isFolder: boolean;
    parent?: null | SimpleTreeItemParentResponse;
};

export type SimpleTreeRenderModel = {
    body: string;
};

export type TargetPagedModelOfSimpleTreeItemResponse = {
    totalBefore: number | string;
    totalAfter: number | string;
    /**
     * Gets the items for the current page.
     */
    items: Array<SimpleTreeItemResponse>;
    /**
     * Gets the total number of items available across all pages.
     */
    total: number | string;
};

export type PostEntityActionExecuteData = {
    body: SimpleEntityActionRequest;
    path?: never;
    query?: never;
    url: '/umbraco/SimpleTrees/api/v1/entity-action/execute';
};

export type PostEntityActionExecuteErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostEntityActionExecuteResponses = {
    /**
     * OK
     */
    200: SimpleEntityActionExecuteResponse;
};

export type PostEntityActionExecuteResponse = PostEntityActionExecuteResponses[keyof PostEntityActionExecuteResponses];

export type PostEntityActionUrlData = {
    body: SimpleEntityActionRequest;
    path?: never;
    query?: never;
    url: '/umbraco/SimpleTrees/api/v1/entity-action/url';
};

export type PostEntityActionUrlErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostEntityActionUrlResponses = {
    /**
     * OK
     */
    200: SimpleEntityActionUrlResponse;
};

export type PostEntityActionUrlResponse = PostEntityActionUrlResponses[keyof PostEntityActionUrlResponses];

export type GetTreeItemsPagedOffsetData = {
    body?: never;
    path?: never;
    query?: {
        treeAlias?: string;
        entityType?: string;
        parentUnique?: string;
        skip?: number | string;
        take?: number | string;
        foldersOnly?: boolean;
    };
    url: '/umbraco/SimpleTrees/api/v1/tree/items/paged-offset';
};

export type GetTreeItemsPagedOffsetErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetTreeItemsPagedOffsetResponses = {
    /**
     * OK
     */
    200: PagedSimpleTreeItemResponseModel;
};

export type GetTreeItemsPagedOffsetResponse = GetTreeItemsPagedOffsetResponses[keyof GetTreeItemsPagedOffsetResponses];

export type GetTreeItemsPagedTargetData = {
    body?: never;
    path?: never;
    query?: {
        treeAlias?: string;
        targetUnique?: string;
        targetEntityType?: string;
        parentUnique?: string;
        entityType?: string;
        takeBefore?: number | string;
        takeAfter?: number | string;
        foldersOnly?: boolean;
    };
    url: '/umbraco/SimpleTrees/api/v1/tree/items/paged-target';
};

export type GetTreeItemsPagedTargetErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetTreeItemsPagedTargetResponses = {
    /**
     * OK
     */
    200: TargetPagedModelOfSimpleTreeItemResponse;
};

export type GetTreeItemsPagedTargetResponse = GetTreeItemsPagedTargetResponses[keyof GetTreeItemsPagedTargetResponses];

export type GetTreeRenderData = {
    body?: never;
    path?: never;
    query?: {
        unique?: string;
        entityType?: string;
    };
    url: '/umbraco/SimpleTrees/api/v1/tree/render';
};

export type GetTreeRenderErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetTreeRenderResponses = {
    /**
     * OK
     */
    200: SimpleTreeRenderModel;
};

export type GetTreeRenderResponse = GetTreeRenderResponses[keyof GetTreeRenderResponses];

export type GetTreeRootPagedOffsetData = {
    body?: never;
    path?: never;
    query?: {
        treeAlias?: string;
        skip?: number | string;
        take?: number | string;
        foldersOnly?: boolean;
    };
    url: '/umbraco/SimpleTrees/api/v1/tree/root/paged-offset';
};

export type GetTreeRootPagedOffsetErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetTreeRootPagedOffsetResponses = {
    /**
     * OK
     */
    200: PagedSimpleTreeItemResponseModel;
};

export type GetTreeRootPagedOffsetResponse = GetTreeRootPagedOffsetResponses[keyof GetTreeRootPagedOffsetResponses];

export type GetTreeRootPagedTargetData = {
    body?: never;
    path?: never;
    query?: {
        treeAlias?: string;
        unique?: string;
        entityType?: string;
        takeBefore?: number | string;
        takeAfter?: number | string;
        foldersOnly?: boolean;
    };
    url: '/umbraco/SimpleTrees/api/v1/tree/root/paged-target';
};

export type GetTreeRootPagedTargetErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetTreeRootPagedTargetResponses = {
    /**
     * OK
     */
    200: TargetPagedModelOfSimpleTreeItemResponse;
};

export type GetTreeRootPagedTargetResponse = GetTreeRootPagedTargetResponses[keyof GetTreeRootPagedTargetResponses];
