// This file is auto-generated by @hey-api/openapi-ts

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PagedSimpleTreeItemResponseModel = {
    total: number;
    items: Array<SimpleTreeItemResponse>;
};

export type SimpleEntityActionExecuteResponse = {
    title: string;
    isSuccess: boolean;
    message: string;
};

export type SimpleEntityActionRequest = {
    unique: string;
    entityType: string;
    actionAlias: string;
};

export type SimpleEntityActionUrlResponse = {
    url: string;
};

export type SimpleTreeItemParentResponse = {
    unique: string;
    entityType?: string | null;
};

export type SimpleTreeItemResponse = {
    name: string;
    icon: string;
    entityType: string;
    unique: string;
    hasChildren: boolean;
    isFolder: boolean;
    parent?: SimpleTreeItemParentResponse | null;
};

export type SimpleTreeRenderModel = {
    body: string;
};

export type PostUmbracoSimpleTreesApiV1EntityActionExecuteData = {
    body?: SimpleEntityActionRequest;
    path?: never;
    query?: never;
    url: '/umbraco/SimpleTrees/api/v1/entity-action/execute';
};

export type PostUmbracoSimpleTreesApiV1EntityActionExecuteResponses = {
    /**
     * OK
     */
    200: SimpleEntityActionExecuteResponse;
};

export type PostUmbracoSimpleTreesApiV1EntityActionExecuteResponse = PostUmbracoSimpleTreesApiV1EntityActionExecuteResponses[keyof PostUmbracoSimpleTreesApiV1EntityActionExecuteResponses];

export type PostUmbracoSimpleTreesApiV1EntityActionUrlData = {
    body?: SimpleEntityActionRequest;
    path?: never;
    query?: never;
    url: '/umbraco/SimpleTrees/api/v1/entity-action/url';
};

export type PostUmbracoSimpleTreesApiV1EntityActionUrlResponses = {
    /**
     * OK
     */
    200: SimpleEntityActionUrlResponse;
};

export type PostUmbracoSimpleTreesApiV1EntityActionUrlResponse = PostUmbracoSimpleTreesApiV1EntityActionUrlResponses[keyof PostUmbracoSimpleTreesApiV1EntityActionUrlResponses];

export type GetUmbracoSimpleTreesApiV1TreeItemsData = {
    body?: never;
    path?: never;
    query?: {
        treeAlias?: string;
        entityType?: string;
        parentUnique?: string;
        skip?: number;
        take?: number;
        foldersOnly?: boolean;
    };
    url: '/umbraco/SimpleTrees/api/v1/tree/items';
};

export type GetUmbracoSimpleTreesApiV1TreeItemsResponses = {
    /**
     * OK
     */
    200: PagedSimpleTreeItemResponseModel;
};

export type GetUmbracoSimpleTreesApiV1TreeItemsResponse = GetUmbracoSimpleTreesApiV1TreeItemsResponses[keyof GetUmbracoSimpleTreesApiV1TreeItemsResponses];

export type GetUmbracoSimpleTreesApiV1TreeRenderData = {
    body?: never;
    path?: never;
    query?: {
        unique?: string;
        entityType?: string;
    };
    url: '/umbraco/SimpleTrees/api/v1/tree/render';
};

export type GetUmbracoSimpleTreesApiV1TreeRenderResponses = {
    /**
     * OK
     */
    200: SimpleTreeRenderModel;
};

export type GetUmbracoSimpleTreesApiV1TreeRenderResponse = GetUmbracoSimpleTreesApiV1TreeRenderResponses[keyof GetUmbracoSimpleTreesApiV1TreeRenderResponses];

export type GetUmbracoSimpleTreesApiV1TreeRootData = {
    body?: never;
    path?: never;
    query?: {
        treeAlias?: string;
        skip?: number;
        take?: number;
        foldersOnly?: boolean;
    };
    url: '/umbraco/SimpleTrees/api/v1/tree/root';
};

export type GetUmbracoSimpleTreesApiV1TreeRootResponses = {
    /**
     * OK
     */
    200: PagedSimpleTreeItemResponseModel;
};

export type GetUmbracoSimpleTreesApiV1TreeRootResponse = GetUmbracoSimpleTreesApiV1TreeRootResponses[keyof GetUmbracoSimpleTreesApiV1TreeRootResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:54813' | (string & {});
};